version: '3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    image: acunathink/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    env_file: .env
    image: acunathink/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: acunathink/foodgram_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/backend/
      - media:/media/
